### ISSUE TITLE
Little visual glitch in album overview

### ISSUE THREAD

**Issue by elea11** [Iamlooker/Howl#10]
**Describe the bug**

**To Reproduce**
1. Go to 'albums'
2. Don't pull down
3. At the very top there's a thin white/colored line as a leftover of the pull down player view at the top, see screenshot

**Expected behavior**
The line shouldn't be visible

**Screenshots**
![Screenshot_20220620-205001.png](https://user-images.githubusercontent.com/61006322/174662994-8109c03a-3435-4aa2-a7f6-e7a081e51ac4.png)

**Smartphone (please complete the following information):**
 - Device: pixel 4a 5g, bramble
 - OS: protonAOSP
 - Version howl 8

**Comment by Iamlooker** [comment]
This will be fixed in next update 😁
