### ISSUE TITLE
Only one song appears in album

### ISSUE THREAD

**Issue by Huddsto** [Iamlooker/Howl#16]
**When open album instead of all songs appears only one track**

![Screenshot_2022-07-07-21-51-31-737_com looker howlmusic](https://user-images.githubusercontent.com/101352910/177850211-c7347ba6-d699-46ac-86e0-2163f85f7f1b.jpg)

**Comment by Huddsto** [comment]
In **Songs** folder all tracks are displayed 

![Screenshot_2022-07-07-21-57-45-766_com looker howlmusic](https://user-images.githubusercontent.com/101352910/177851157-a0c73712-7fc6-4870-89d1-553d547390ef.jpg)

**Comment by Iamlooker** [comment]
Fixed here 4679513eacfb42f140ac92a733bc76e99c670648
