### ISSUE TITLE
Wrong APK attached to v0.2.8 release

### ISSUE THREAD

**Issue by IzzySoft** [Iamlooker/Howl#19]
Just a note: The APK attached to release v0.2.8 identifies as

    package: name='com.looker.howlmusic' versionCode='10' versionName='0.2.7' compileSdkVersion='33' compileSdkVersionCodename='13'

Shouldn't that read '0.2.8' resp.  '11'? Could it be the wrong APK got attached there?

**Comment by Iamlooker** [comment]
Ooh I will fix this today

**Comment by Iamlooker** [comment]
I created a new release so this should be fixed

New version is 0.2.9

**Comment by IzzySoft** [comment]
Thanks! That worked out, new version has been picked successfully by my updater and became available [in my repo](https://apt.izzysoft.de/fdroid/index/apk/com.looker.howlmusic). Btw: if you like to link there (users can fetch it with their [F-Droid client](https://android.izzysoft.de/applists/category/named/apps_markets#group_1181) and keep it updated automatically, always being informed about updates), be welcome to [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) for that :wink:
