### ISSUE TITLE
Items sort options

### ISSUE THREAD

**Issue by telumletiferum** [Iamlooker/Howl#8]
For now the app sorts all the items in an album in alphabetical order (A-Z), and there is no way to change that sorting.
I would like for the app to have different sorting options, mostly I want to see disc and track number sorting, as that is, I think, 99.9% of how people listen to music.

As for how to implement it, I think there are 2 ways. Making another Floating Action Button that opens an individual settings page or have a tiny button in the album view, where you can change the default sorting options for all albums.
I am more in favour of the second option as it allows to keep the very minimalistic look of app and make minimal changes.

**Comment by Iamlooker** [comment]
Sure I will look into this in near future

**Comment by Iamlooker** [comment]
This will also be added after few updates.
Currently I am busy irl.

**Comment by telumletiferum** [comment]
Does this deserved to be closed? I still like the main sorting option you should aim for is disc and track sorting because as I said, that's mainly how people listen to music.
